project:
  type: website
  render:
  - "*.qmd"
  - "!Processing.qmd"
  output-dir: docs/
website:
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Please see left-sidebar for definitions"
    type: info
    position: below-navbar  
  google-analytics:
    tracking-id: "G-K91JKBNH5N"
  title: "Cairo Lab: Unmixing Control Monitoring"
  navbar:
    logo: images/hex.png
    left:
    - text: "Home"
      href: index.qmd
    - text: "Panel"
      menu:
      - text: "Myeloid"
        href: Myeloid.qmd
      - text: "Bcells"
        href: Bcells.qmd
      - text: "AlphaBeta"
        href: AlphaBeta.qmd
      - text: "ILTs"
        href: ILTs.qmd
    right:
    - text: "Help"
      href: help.qmd
    - icon: github
      href: https://github.com/DavidRach/SingleColors
      aria-label: GitHub
  page-footer:
    background: light
    left: University of Maryland, Baltimore
    right: Built with [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme: styles.scss