---
format:
  dashboard:
    orientation: columns
project:
  output-dir: docs/
---

Myeloid Panel

## {.sidebar}

**About**

This dashboard contains visualized data from respective panels unmixing controls, as well as relavent instrumental data for the 5 laser Cytek Aurora at the [UMGCC FCSS](https://umgccfcss.github.io/InstrumentQC/)

This dashboard was created with [Quarto](https://quarto.org/) and is maintained by [David Rach](https://github.com/DavidRach)

## Laser {width="50%"}

```{r}
#| title: UltraViolet
#| icon: cup-hot
#| content: valuebox
library(htmltools)
HTML("
<ul>
  <li><a href='Myeloid/BUV395_CD18.html'>BUV395 CD18</a></li>
  <li><a href='Myeloid/BUV496_CCR2.html'>BUV496 CCR2</a></li>
  <li><a href='Myeloid/BUV563_CCR2.html'>BUV563 CCR2</a></li>
  <li><a href='Myeloid/BUV615_CD89.html'>BUV615 CD89</a></li>
  <li><a href='Myeloid/BUV737_CD38.html'>BUV737 CD38</a></li>
  <li><a href='Myeloid/BUV805_CD3.html'>BUV805 CD3</a></li>
</ul>
")

```

```{r}
#| title: Violet
#| icon: cup-hot
#| content: valuebox

HTML("
<ul>
  <li><a href='Myeloid/BV570_CD16.html'>BV570 CD16</a></li>
  <li><a href='Myeloid/BV605_CD56.html'>BV605 CD56</a></li>
  <li><a href='Myeloid/BV711_FceR1a.html'>BV711 FceR1a</a></li>
  <li><a href='Myeloid/BV750_CD303.html'>BV750 CD303</a></li>
  <li><a href='Myeloid/BV785_CD141.html'>BV785 CD141</a></li>
</ul>
")

```

::: {.card title=""}

:::

## Second Column
```{r}
#| title: Blue
#| icon: cup-hot
#| content: valuebox

HTML("
<ul>
  <li><a href='Myeloid/FITC_CD11b.html'>FITC CD11b</a></li>
  <li><a href='Myeloid/PerCPCy55_CD123.html'>PerCP-Cy5.5 CD123</a></li>
</ul>
")

```

```{r}
#| title: YellowGreen
#| icon: cup-hot
#| content: valuebox

HTML("
<ul>
  <li><a href='Myeloid/PEDazzle594_CD1c.html'>PE-Dazzle 594 CD1c</a></li>
  <li><a href='Myeloid/cFluorBYG750_CD19.html'>cFluor BYG750 CD19</a></li>
</ul>
")

```

```{r}
#| title: Red
#| icon: cup-hot
#| content: valuebox

HTML("
<ul>
  <li><a href='Myeloid/AF647_CD163.html'>Alexa Fluor 647 CD163</a></li>
  <li><a href='Myeloid/R718_CD32.html'>R718 CD32</a></li>
  <li><a href='Myeloid/APCFire750_CD4.html'>APC-Fire 750 CD4</a></li>
  <li><a href='Myeloid/APCFire810_CD64.html'>APC-Fire 810 CD64</a></li>
</ul>
")

```


