---
title: "ProcessingScript"
format: html
---
```{r}
library(stringr)
```

```{r}
Folder <- file.path("/media", "david", "DavidRach", "SingleColors", "Myeloid_DHIM")
Subset <- file.path(Folder, "Aug1")

UnstainedBeads <- "Beads\\Unstained"
UnstainedBeads <- list.files(Folder, UnstainedBeads, full.names=TRUE, recursive=TRUE)
Dates1 <- str_extract(UnstainedBeads, "(?<=DHIM/)[^/]+(?=/Beads)")

Fluorophore <- "Alexa Fluor 647"
Beads <- list.files(Folder, Fluorophore, full.names=TRUE, recursive=TRUE)
Beads <- Beads[grep("Beads", Beads)]
Dates2 <- str_extract(Beads, "(?<=DHIM/)[^/]+(?=/CD163)")

if (length(Dates1) != length(Dates2)){stop("Different number of unstained to single color controls")}
```

```{r}
library(flowCore)
library(flowWorkspace)
library(openCyto)
library(Luciernaga)
library(purrr)
library(dplyr)

x <- Dates1[1]
UnstainedList <- UnstainedBeads
FluorophoreList <- Beads
Multiple = FALSE
removestrings=".fcs"

#File_Location <- system.file("extdata", package = "Luciernaga")
#BeadGateCSV <- list.files(File_Location, pattern="GatesBeads.csv", full.names = TRUE)
#GateTemplatePath <- BeadGateCSV
#write.csv(TheGates, "BeadGates.csv", row.names=FALSE)
CSVPath <- getwd()
GateTemplatePath <- file.path(CSVPath, "BeadGates.csv")
```

```{r}
#FileLocation <- system.file("extdata", package = "Luciernaga")
#pattern = "AutofluorescentOverlaps.csv"
#AFOverlap <- list.files(path=FileLocation, pattern=pattern, full.names = TRUE)
AFOverlap <- read.csv("BeadAFOverlap.csv", check.names=FALSE)
#write.csv(AFOverlap, "BeadAFOverlap.csv", row.names=FALSE)
```

```{r}
LuciernagaWrapper <- function(x, UnstainedList, FluorophoreList, Multiple=FALSE,
    GateTemplatePath, removestrings=".fcs", AFOverlap){

    Value <- paste0(x, "(?!\\d)")
    Unstained <- UnstainedList[str_detect(UnstainedList, Value, negate = FALSE)]
    Fluorophore <- FluorophoreList[str_detect(FluorophoreList, Value, negate = FALSE)]

    if (Multiple == FALSE){
     if (length(Fluorophore) != length(Unstained)){
        stop("Mismatch unstained vs stained")}
    }

    files <- c(Unstained, Fluorophore)
    cs <- load_cytoset_from_fcs(files, truncate_max_range = FALSE, transformation = FALSE)
    gs <- GatingSet(cs)

    TheGates <- data.table::fread(GateTemplatePath)
    TheGating <- gatingTemplate(TheGates)
    gt_gating(TheGating, gs)

    Plot <- map(.x=gs, .f=Utility_GatingPlots, sample.name=c("GROUPNAME", "TUBENAME"), removestrings=removestrings, subset="root", gtFile=TheGates, DesiredGates=NULL,
    outpath = NULL, returnType="patchwork", therows=2, thecolumns=2)

    pd <- pData(gs)
    Names <- pData(gs)$name
    Unstained <- str_detect(Names, "Unstained")
    Unstained <- data.frame(Unstained, check.names=FALSE)
    newpd <- cbind(pd, Unstained)
    pData(gs) <- newpd

    TheUnstained <- subset(gs, Unstained == TRUE)
    TheFluorophore <- subset(gs, Unstained == FALSE)

    UnstainedBeads <- Luciernaga_QC(x=TheUnstained[1], desiredAF = NULL,
                    subsets="singlets", removestrings=removestrings,
                    sample.name="GUID", unmixingcontroltype = "beads",
                    Unstained = TRUE, ratiopopcutoff = 0.01, Verbose = FALSE,
                    AFOverlap = AFOverlap, stats = "median",
                    ExportType = "data.frame", SignatureReturnNow = TRUE,
                    outpath = NULL)
    
    FluorophoreSignature <- map(.x=TheFluorophore, .f=Luciernaga_QC,
        subsets="singlets", removestrings=removestrings, sample.name="GUID",
        unmixingcontroltype = "beads", Unstained = FALSE, ratiopopcutoff = 0.01, Verbose = FALSE, AFOverlap = AFOverlap, stats = "median", 
        ExportType = "data", SignatureReturnNow = FALSE,
        outpath = NULL, Increments=0.1, SecondaryPeaks=2, experiment = x,
        condition = x, SCData="subtracted", NegativeType="default", BeadAF=UnstainedBeads, BeadMainAF="UV1-A") |> bind_rows()
    
    TheReturns <- list(Plot=Plot, data=FluorophoreSignature)

    return(TheReturns)
}
```

```{r}
Iterated <- map(.x=Dates1, .f=LuciernagaWrapper, UnstainedList=UnstainedBeads, FluorophoreList=Beads, Multiple=FALSE, GateTemplatePath=GateTemplatePath, AFOverlap=AFOverlap)
```

```{r}
Iterated

ThePlots <- lapply(Iterated, function(x) x$Plot)
TheData <- lapply(Iterated, function(x) x$data)
TheDataset <- bind_rows(TheData)
#View(TheDataset)
```
